on: push
name: CI
jobs:
  deploy:
    runs-on: ubuntu-latest
    container:
      image: kirschbaumdevelopment/laravel-test-runner:8.1
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
 
    - name: Install composer dependencies
      run: |
        composer install --no-ansi --no-dev --no-interaction --no-plugins --no-scripts --optimize-autoloader
 
    - name: Prepare Laravel Application
      run: |
        cp .env.prod .env
        php artisan key:generate
        php please install
 
    - name: Install front-end dependencies
      run: |
        npm install
        npm run production

    - name: Production Deployment
      uses: burnett01/rsync-deployments@5.2
      with:
        switches: -avzr --delete --exclude={'users/','content/'}
        path: ./
        remote_path: ${{ secrets.REMOTE_TARGET }}
        remote_host: ${{ secrets.REMOTE_HOST }}
        remote_user: ${{ secrets.REMOTE_USER }}
        remote_key: ${{ secrets.PRIVATE_KEY }}